import { EgressClient, EgressStatus } from 'livekit-server-sdk';
import { NextRequest, NextResponse } from 'next/server';

export async function GET(req: NextRequest) {
  try {
    const roomName = req.nextUrl.searchParams.get('roomName');

    /**
     * CAUTION:
     * for simplicity this implementation does not authenticate users and therefore allows anyone with knowledge of a roomName
     * to start/stop recordings for that room.
     * DO NOT USE THIS FOR PRODUCTION PURPOSES AS IS
     */

    if (roomName === null) {
      return new NextResponse('Missing roomName parameter', { status: 403 });
    }

    const { LIVEKIT_API_KEY, LIVEKIT_API_SECRET, LIVEKIT_URL } = process.env;

    const hostURL = new URL(LIVEKIT_URL!);
    hostURL.protocol = 'https:';

    const egressClient = new EgressClient(hostURL.origin, LIVEKIT_API_KEY, LIVEKIT_API_SECRET);
    const activeEgresses = (await egressClient.listEgress({ roomName })).filter(
      (info) => info.status < 2,
    );
    if (activeEgresses.length === 0) {
      return new NextResponse('No active recording found', { status: 404 });
    }

    // Stop all active egresses
    const egressId = activeEgresses[0].egressId;
    console.log(`[Record Stop] Stopping egress ${egressId} for room ${roomName}`);
    await Promise.all(activeEgresses.map((info) => egressClient.stopEgress(info.egressId)));

    // Poll for completion (max 2 minutes)
    const maxWaitTime = 120000; // 2 minutes
    const pollInterval = 2000; // 2 seconds
    const startTime = Date.now();

    let egressInfo;
    let pollCount = 0;
    while (Date.now() - startTime < maxWaitTime) {
      pollCount++;
      // List egress to get current status
      const allEgress = await egressClient.listEgress({ egressId });
      egressInfo = allEgress[0];

      if (!egressInfo) {
        console.error(`[Record Stop] Egress ${egressId} not found after ${pollCount} polls`);
        return new NextResponse('Egress not found', { status: 404 });
      }

      console.log(
        `[Record Stop] Poll ${pollCount}: status=${egressInfo.status}, fileResults=${egressInfo.fileResults?.length || 0}`,
      );

      if (egressInfo.status === EgressStatus.EGRESS_COMPLETE) {
        console.log(`[Record Stop] Egress completed after ${pollCount} polls`);
        break;
      }

      if (egressInfo.status > EgressStatus.EGRESS_COMPLETE) {
        // Status is beyond complete, likely failed or aborted
        console.error(
          `[Record Stop] Recording failed with status: ${egressInfo.status}, error: ${egressInfo.error}`,
        );
        return new NextResponse(
          `Recording failed with status: ${egressInfo.status} - ${egressInfo.error || 'Unknown error'}`,
          { status: 500 },
        );
      }

      await new Promise((resolve) => setTimeout(resolve, pollInterval));
    }

    if (!egressInfo || egressInfo.status !== EgressStatus.EGRESS_COMPLETE) {
      console.error(
        `[Record Stop] Recording did not complete in time. Last status: ${egressInfo?.status}`,
      );
      return new NextResponse('Recording did not complete in time', { status: 408 });
    }

    // Get the presigned URL from file results (generated by egress)
    const fileResult = egressInfo.fileResults[0];
    console.log(
      `[Record Stop] File result - location: ${fileResult?.location}, filename: ${fileResult?.filename}`,
    );

    if (!fileResult || !fileResult.location) {
      console.error('[Record Stop] No file location found in egress result');
      return new NextResponse('Recording completed but no file location found', { status: 500 });
    }

    const recordingUrl = fileResult.location;
    console.log(`[Record Stop] Recording URL: ${recordingUrl}`);

    // Return the recording URL to the client so it can send it to chat
    return new NextResponse(JSON.stringify({ url: recordingUrl }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (error) {
    if (error instanceof Error) {
      return new NextResponse(error.message, { status: 500 });
    }
  }
}
